import './global.css'
import styles from './root.module.css'
import isAuth from '@/utils/isAuth'
import Navbar from '@/features/navbar/Navbar'

export const metadata = {
  title: 'Switter',
  description: 'Generated by Next.js',
  icons: {
    icon: '/logo.png',
  },
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const auth = await isAuth()

  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          {auth && <Navbar auth={auth}/>}
          {children}
        </div>
      </body>
    </html>
  )
}
